hasCJKLanguage = true
DefaultContentLanguage = "ja"


baseURL = "https://matsuuratomoya.com/"
title = "Matsuura Tomoya"
enableMissingTranslationPlaceholders = false
enableGitInfo = true
publishDir = "docs"
theme = "tomoya-2019"
[markup.goldmark.renderer]
  unsafe = true
[permalinks]
  blog = "/:section/:year-:month-:day/:filename/"
  info = "/:section/:year-:month-:day/:filename/"
[params]
  Twitter = "tomoya_nonymous"
  Facebook = "tomoya.matsuura.98"
  Github = "tomoyanonymous"
  Instagram = "tomoya_nonymous"
  Vimeo = "tomoyamatsuura"
  Soundcloud = "tomoya_matsuura"
  description = "松浦知也のWebサイトです。"
  ogpimage = "assets/img/image_ogp.png"
[[menu.main]]
  name = "About"
  url = "about"
  weight = 1
[[menu.main]]
  name = "Info"
  url = "info"
  weight = 2
[[menu.main]]
  name = "Works"
  url = "works"
  weight = 3
[[menu.main]]
  name = "Research"
  url = "research"
  weight = 4
[[menu.main]]
  name = "Blog"
  url = "blog"
  weight = 5
[[menu.main]]
  name = "Teaching"
  url = "https://teach.matsuuratomoya.com"
  weight = 6 
[[menu.main]]
  name = "Contact"
  url = "contact"
  weight = 7

[languages]
[languages.ja]
weight = 1
languageCode = "ja"


[languages.en]
weight = 2
[languages.en.params]
description = "Website of Matsuura Tomoya."


