[build]
publish = "docs"
command = "pushd themes/tomoya-2023 && npm install && popd && hugo --minify --gc"

[context.deploy-preview]
command = "pushd themes/tomoya-2023 && npm install && popd && hugo --minify --gc -b $DEPLOY_URL"

[build.environment]
HUGO_VERSION = "v0.135.0"
NODE_VERSION = "20.5.1"
NPM_VERSION = "10.4.0"